import {
  BiDownArrowAlt,
  BiHomeAlt,
  BiSearch,
  BiUpArrowAlt,
} from 'react-icons/bi';
import DashboardIcon from '../../components/Icons/DashboardIcon';
import {
  Add,
  ArrowDown,
  Magicpen,
  ArrowLeft,
  ArrowDown2,
  ArrowRight,
  ArrowUp,
  ArrowUp2,
  Box1,
  Briefcase,
  Bubble,
  Calendar,
  CalendarEdit,
  Call,
  ClipboardText,
  CloseCircle,
  Colorfilter,
  DocumentCopy,
  Edit2,
  Eye,
  EyeSlash,
  Folder,
  Gallery,
  HambergerMenu,
  Link21,
  Lock,
  Message,
  Minus,
  MenuBoard,
  Mobile,
  Mouse,
  Profile2User,
  SearchNormal1,
  Sms,
  Sort,
  Text,
  User,
  Paintbucket,
  Verify,
  Back,
  ArrowForward,
  ClipboardTick,
  MobileProgramming,
  DocumentText,
  TextBold,
  TextItalic,
  Setting,
  Setting2,
} from 'iconsax-react';
import { Notification as NotificationIcon } from 'iconsax-react';
import ArrowIcon from '../../components/Icons/ArrowIcon';
import { BsThreeDotsVertical, BsEnvelopeOpen, BsDownload } from 'react-icons/bs';
import { FiPower } from 'react-icons/fi';
import { FaCheck } from 'react-icons/fa6';
import { DeleteIcon } from '@chakra-ui/icons';

const APP_ICONS = {
  DASHBOARD: DashboardIcon,
  USERS: Profile2User,
  USER2: User,
  LOCK: Lock,
  CLIENTS: Briefcase,
  PROJECTS: Folder,
  TOOLS: Box1,
  SOCIAL_MEDIA_PLANNER: CalendarEdit,
  SEARCH: BiSearch,
  DOWNLOAD:BsDownload,
  CLIPBOARD: ClipboardText,
  MESSAGE: Message,
  NOTIFICATION: NotificationIcon,
  MAP: BiHomeAlt,
  SETTINGS: BiHomeAlt,
  EYE: Eye,
  EYE_OFF: EyeSlash,
  POWER: FiPower,
  FOLDER: Folder,
  GALLERY: Gallery,
  LINK: Link21,
  GNERATE: Magicpen,
  CALL: Call,
  MAIL: Sms,
  EMAIL: BsEnvelopeOpen,
  SCREEN: Mobile,
  MOUSE: Mouse,
  FILL: Paintbucket,
  COLORFILTER: Colorfilter,
  BUBBLE: Bubble,
  TEXT: Text,
  MENUBOARD: MenuBoard,
  UNDO: Back,
  REDO: ArrowForward,
  BOLD: TextBold,
  ITALIC: TextItalic,
  CHECK: FaCheck,
  CALENDAR: Calendar,
  CLIPBOARD: ClipboardTick,
  MOBILE: MobileProgramming,
  GEAR: Setting2,
  DOCUMENT: DocumentText,

  //ACTIONS
  ADD: Add,
  MINUS: Minus,
  COPY: DocumentCopy,
  MORE_OPTIONS: BsThreeDotsVertical,
  MENU: HambergerMenu,
  EDIT: Edit2,
  CLOSE: CloseCircle,
  FILTER: Sort,
  BIN: DeleteIcon,
  APPROVE: Verify,

  //DIRECTIONAL
  ARROW: ArrowIcon,
  ARROW_LEFT: ArrowLeft,
  ARROW_RIGHT: ArrowRight,
  DownArrow: BiDownArrowAlt,
  UpArrow: BiUpArrowAlt,
  DOWN_CHEVRON: ArrowDown2,
  UP_CHEVRON: ArrowUp2,
};

export default APP_ICONS;
